---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kinoamped
description: Personal Kinoite image with NVIDIA open drivers and development tools.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: akmods
    install: []
    nvidia-driver: nvidia-open

  - type: dnf
    repos:
      files:
        - https://download.docker.com/linux/fedora/docker-ce.repo
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        - podman-compose
        - mullvad-vpn
        - mullvad-browser
        - tailscale
        - kde-gtk-config
        - neovim
        - btop
        - wireguard-tools
        - desktop-backgrounds-kde
        - f38-backgrounds-kde
        - f38-backgrounds-extras-kde
        - f39-backgrounds-kde
        - f39-backgrounds-extras-kde
        - f40-backgrounds-kde
        - f40-backgrounds-extras-kde
        - f41-backgrounds-kde
        - f42-backgrounds-kde
        - f43-backgrounds-kde
        - f44-backgrounds-kde

  - type: systemd
    system:
      enabled:
        - docker.service
        - mullvad-daemon.service
        - tailscaled.service

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
      - scope: user

  - type: signing
