---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kinoamped
description: Personal Kinoite image with NVIDIA open drivers.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: akmods
    install: []
    nvidia-driver: nvidia-open

  - type: dnf
    install:
      packages:
        - distrobox
        - starship
        - nvidia-container-toolkit

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
      - scope: user

  - type: signing
